#!/bin/bash

docker build -t microservices-app-frontend .;
docker stop `docker ps | grep ':80' | awk '{ print $1 }'`;
docker run -d -p 127.0.0.1:80:80 --restart unless-stopped microservices-app-frontend;
